data:
  image_dir: "/kaggle/input/road-sign-detection/images"
  annotation_dir: "/kaggle/input/road-sign-detection/annotations"
  
model:
  input_size: [224, 224, 3]
  num_classes: 10
  
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
